[package]
name = "actix-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "actix-example"
path = "src/main.rs"

[dependencies]
trueflow-runtime = { path = "../../trueflow-runtime" }
trueflow-macros = { path = "../../trueflow-macros" }
actix-web = "4"
actix-rt = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
